// @ts-check

import orderRules from "./order-rules.js";

/** @type {import("./types.js").Rules} */
const rules = {
	"order/properties-order": orderRules,

	"annotation-no-unknown": [true, { ignoreAnnotations: ["default", "global", "optional"] }],
	"at-rule-descriptor-no-unknown": null,
	"at-rule-descriptor-value-no-unknown": null,
	"at-rule-no-deprecated": [true, { severity: "warning" }],
	"at-rule-no-unknown": [
		true,
		{
			ignoreAtRules: [
				"at-root",
				"content",
				"debug",
				"each",
				"else",
				"error",
				"extend",
				"for",
				"forward",
				"function",
				"if",
				"import",
				"include",
				"mixin",
				"return",
				"use",
				"warn",
				"while",
			],
		},
	],
	"at-rule-prelude-no-invalid": null,
	"block-no-empty": [true, { ignore: ["comments"] }, { severity: "warning" }],
	"color-no-invalid-hex": true,
	"comment-no-empty": null,
	"custom-property-no-missing-var-function": true,
	"declaration-block-no-duplicate-custom-properties": true,
	"declaration-block-no-duplicate-properties": [true, { severity: "warning" }],
	"declaration-block-no-shorthand-property-overrides": true,
	"declaration-property-value-keyword-no-deprecated": [true, { severity: "warning" }],
	"declaration-property-value-no-unknown": null,
	"font-family-no-duplicate-names": true,
	"font-family-no-missing-generic-family-keyword": true,
	"function-calc-no-unspaced-operator": [true, { severity: "warning" }],
	"function-linear-gradient-no-nonstandard-direction": true,
	"function-no-unknown": null,
	"keyframe-block-no-duplicate-selectors": true,
	"keyframe-declaration-no-important": true,
	"media-feature-name-no-unknown": true,
	"media-feature-name-value-no-unknown": null,
	"media-query-no-invalid": null,
	"media-type-no-deprecated": true,
	"named-grid-areas-no-invalid": true,
	"nesting-selector-no-missing-scoping-root": null,
	"no-descending-specificity": true,
	"no-duplicate-at-import-rules": true,
	"no-duplicate-selectors": [true, { severity: "warning" }],
	"no-empty-source": true,
	"no-invalid-double-slash-comments": true,
	"no-invalid-position-at-import-rule": [
		true,
		{
			ignoreAtRules: ["use", "forward", "mixin"],
		},
	],
	"no-invalid-position-declaration": true,
	"no-irregular-whitespace": true,
	"no-unknown-animations": true,
	"no-unknown-custom-media": true,
	"no-unknown-custom-properties": null,
	"property-no-deprecated": [true, { severity: "warning" }],
	"property-no-unknown": null,
	"selector-anb-no-unmatchable": true,
	"selector-pseudo-class-no-unknown": null,
	"selector-pseudo-element-no-unknown": true,
	"selector-type-no-unknown": true,
	"string-no-newline": [true, { ignore: ["at-rule-preludes", "declaration-values"] }],
	"syntax-string-no-invalid": true,
	"unit-no-unknown": true,
	"alpha-value-notation": ["number", { severity: "warning" }],
	"at-rule-allowed-list": null,
	"at-rule-disallowed-list": null,
	"at-rule-empty-line-before": [
		"always",
		{
			except: ["blockless-after-same-name-blockless", "blockless-after-blockless", "first-nested"],
			ignore: ["after-comment"],
			ignoreAtRules: ["else"],
			severity: "warning",
		},
	],
	"at-rule-no-vendor-prefix": [true, { severity: "warning" }],
	"at-rule-property-required-list": null,
	"block-no-redundant-nested-style-rules": true,
	"color-function-alias-notation": ["without-alpha", { severity: "warning" }],
	"color-function-notation": ["modern", { severity: "warning" }],
	"color-hex-alpha": "never",
	"color-hex-length": ["long", { severity: "warning" }],
	"color-named": null,
	"color-no-hex": null,
	"comment-empty-line-before": [
		"always",
		{
			except: ["first-nested"],
			ignore: ["stylelint-commands"],
			severity: "warning",
		},
	],
	"comment-pattern": null,
	"comment-whitespace-inside": ["always", { severity: "warning" }],
	"comment-word-disallowed-list": null,
	"custom-media-pattern": ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
	"custom-property-empty-line-before": [
		"always",
		{
			except: ["after-custom-property", "first-nested"],
			ignore: ["after-comment", "inside-single-line-block"],
			severity: "warning",
		},
	],
	"custom-property-pattern": ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
	"container-name-pattern": ["^(--)?([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
	"declaration-block-no-redundant-longhand-properties": [true, { severity: "warning" }],
	"declaration-block-single-line-max-declarations": 1,
	"declaration-empty-line-before": [
		"always",
		{
			except: ["after-declaration", "first-nested"],
			ignore: ["after-comment", "inside-single-line-block"],
			severity: "warning",
		},
	],
	"declaration-no-important": null,
	"declaration-property-max-values": null,
	"declaration-property-unit-allowed-list": null,
	"declaration-property-unit-disallowed-list": null,
	"declaration-property-value-allowed-list": null,
	"declaration-property-value-disallowed-list": null,
	"font-family-name-quotes": ["always-where-recommended", { severity: "warning" }],
	"font-weight-notation": ["numeric", { severity: "warning" }],
	"function-allowed-list": null,
	"function-disallowed-list": null,
	"function-name-case": ["lower", { severity: "warning" }],
	"function-url-no-scheme-relative": true,
	"function-url-quotes": ["always", { severity: "warning" }],
	"function-url-scheme-allowed-list": null,
	"function-url-scheme-disallowed-list": null,
	"hue-degree-notation": ["angle", { severity: "warning" }],
	"import-notation": ["string", { severity: "warning" }],
	"keyframes-name-pattern": ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
	"keyframe-selector-notation": ["percentage-unless-within-keyword-only-block", { severity: "warning" }],
	"layer-name-pattern": ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
	"length-zero-no-unit": [
		true,
		{
			ignore: ["custom-properties"],
			ignorePreludeOfAtRules: ["function", "mixin"],
			severity: "warning",
		},
	],
	"lightness-notation": ["percentage", { severity: "warning" }],
	"max-nesting-depth": null,
	"media-feature-name-allowed-list": null,
	"media-feature-name-disallowed-list": null,
	"media-feature-name-no-vendor-prefix": [true, { severity: "warning" }],
	"media-feature-range-notation": ["context", { severity: "warning" }],
	"media-feature-name-unit-allowed-list": null,
	"media-feature-name-value-allowed-list": null,
	"number-max-precision": 4,
	"property-allowed-list": null,
	"property-disallowed-list": null,
	"property-no-vendor-prefix": [true, { severity: "warning" }],
	"rule-empty-line-before": [
		"always-multi-line",
		{
			except: ["first-nested"],
			ignore: ["after-comment"],
			severity: "warning",
		},
	],
	"rule-selector-property-disallowed-list": null,
	"selector-attribute-quotes": ["always", { severity: "warning" }],
	"selector-max-attribute": null,
	"selector-max-class": null,
	"selector-max-combinators": null,
	"selector-max-compound-selectors": null,
	"selector-max-id": 0,
	"selector-max-pseudo-class": null,
	"selector-max-specificity": null,
	"selector-max-type": null,
	"selector-max-universal": null,
	"selector-not-notation": ["complex", { severity: "warning" }],
	"selector-attribute-name-disallowed-list": null,
	"selector-attribute-operator-allowed-list": null,
	"selector-attribute-operator-disallowed-list": null,
	"selector-class-pattern": null,
	"selector-combinator-allowed-list": null,
	"selector-combinator-disallowed-list": null,
	"selector-disallowed-list": null,
	"selector-id-pattern": ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
	"selector-nested-pattern": null,
	"selector-no-vendor-prefix": [true, { severity: "warning" }],
	"selector-pseudo-class-allowed-list": null,
	"selector-pseudo-class-disallowed-list": null,
	"selector-pseudo-element-allowed-list": null,
	"selector-pseudo-element-colon-notation": ["double", { severity: "warning" }],
	"selector-pseudo-element-disallowed-list": null,
	"selector-type-case": ["lower", { severity: "warning" }],
	"shorthand-property-no-redundant-values": [true, { severity: "warning" }],
	"time-min-milliseconds": null,
	"unit-allowed-list": null,
	"unit-disallowed-list": ["dppx", "q", "mm", "dpcm", "cm", "dpi", "in", "pt", "pc", "ex"],
	"value-keyword-case": ["lower", { severity: "warning" }],
	"value-no-vendor-prefix": [true, { severity: "warning" }],
};
export default rules;
