// @ts-check

/** @type {import("./types").Rules} */
const scssRules = {
	"scss/at-each-key-value-single-line": true,
	"scss/at-else-closing-brace-newline-after": ["always-last-in-chain", { severity: "warning" }],
	"scss/at-else-closing-brace-space-after": ["always-intermediate", { severity: "warning" }],
	"scss/at-else-empty-line-before": ["never", { severity: "warning" }],
	"scss/at-else-if-parentheses-space-before": ["always", { severity: "warning" }],
	"scss/at-extend-no-missing-placeholder": true,
	"scss/at-function-named-arguments": "never",
	"scss/at-function-parentheses-space-before": ["never", { severity: "warning" }],
	"scss/at-function-pattern": ["^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
	"scss/at-if-closing-brace-newline-after": ["always-last-in-chain", { severity: "warning" }],
	"scss/at-if-closing-brace-space-after": ["always-intermediate", { severity: "warning" }],
	"scss/at-if-no-null": true,
	"scss/at-import-partial-extension-allowed-list": null,
	"scss/at-import-partial-extension-disallowed-list": null,
	"scss/at-mixin-argumentless-call-parentheses": ["never", { severity: "warning" }],
	"scss/at-mixin-named-arguments": "never",
	"scss/at-mixin-no-risky-nesting-selector": true,
	"scss/at-mixin-parentheses-space-before": ["never", { severity: "warning" }],
	"scss/at-mixin-pattern": ["^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
	"scss/at-rule-conditional-no-parentheses": [true, { severity: "warning" }],
	"scss/at-rule-no-unknown": true,
	"scss/at-use-no-redundant-alias": true,
	"scss/at-use-no-unnamespaced": null,
	"scss/block-no-redundant-nesting": null,
	"scss/comment-no-empty": true,
	"scss/comment-no-loud": true,
	"scss/declaration-nested-properties-no-divided-groups": true,
	"scss/declaration-nested-properties": "never",
	"scss/declaration-property-value-no-unknown": true,
	"scss/dimension-no-non-numeric-values": true,
	"scss/dollar-variable-colon-newline-after": ["always-multi-line", { severity: "warning" }],
	"scss/dollar-variable-colon-space-after": ["at-least-one-space", { severity: "warning" }],
	"scss/dollar-variable-colon-space-before": ["never", { severity: "warning" }],
	"scss/dollar-variable-default": null,
	"scss/dollar-variable-empty-line-after": ["always", { except: "before-dollar-variable", severity: "warning" }],
	"scss/dollar-variable-empty-line-before": [
		"always",
		{
			except: ["after-dollar-variable", "first-nested"],
			severity: "warning",
		},
	],
	"scss/dollar-variable-first-in-block": null,
	"scss/dollar-variable-no-missing-interpolation": true,
	"scss/dollar-variable-no-namespaced-assignment": null,
	"scss/dollar-variable-pattern": ["^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
	"scss/double-slash-comment-empty-line-before": [
		"always",
		{
			except: ["first-nested"],
			ignore: ["between-comments", "stylelint-commands"],
			severity: "warning",
		},
	],
	"scss/double-slash-comment-inline": null,
	"scss/double-slash-comment-whitespace-inside": ["always", { severity: "warning" }],
	"scss/function-calculation-no-interpolation": true,
	"scss/function-color-channel": true,
	"scss/function-color-relative": true,
	"scss/function-disallowed-list": null,
	"scss/function-no-unknown": null,
	"scss/function-quote-no-quoted-strings-inside": [true, { severity: "warning" }],
	"scss/function-unquote-no-unquoted-strings-inside": [true, { severity: "warning" }],
	"scss/load-no-partial-leading-underscore": true,
	"scss/load-partial-extension": ["never", { severity: "warning" }],
	"scss/map-keys-quotes": "always",
	"scss/media-feature-value-dollar-variable": null,
	"scss/no-dollar-variables": null,
	"scss/no-duplicate-dollar-variables": true,
	"scss/no-duplicate-load-rules": true,
	"scss/no-duplicate-mixins": true,
	"scss/no-global-function-names": true,
	"scss/no-unused-private-members": true,
	"scss/operator-no-newline-after": true,
	"scss/operator-no-newline-before": true,
	"scss/operator-no-unspaced": true,
	"scss/partial-no-import": true,
	"scss/percent-placeholder-pattern": ["^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
	"scss/property-no-unknown": true,
	"scss/selector-nest-combinators": null,
	"scss/selector-no-redundant-nesting-selector": null,
	"scss/selector-no-union-class-name": null,
};
export default scssRules;
